USE DBTEST;

DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS(
	CODIGOPRODUCTO INT auto_increment,
    NOMBREPRODUCTO VARCHAR(30) NOT NULL,
    COSTO DECIMAL NOT NULL DEFAULT 0.0,
    PRECIO FLOAT NOT NULL DEFAULT 0.0,
    PRIMARY KEY PK_PRODUCTOS (CODIGOPRODUCTO)
    );
    
    INSERT INTO PRODUCTOS (NOMBREPRODUCTO, COSTO, PRECIO)
    VALUES ("REGLA", 2.50, 5.00);
    INSERT PRODUCTOS (NOMBREPRODUCTO, COSTO, PRECIO)
    VALUES("CUADERNO UNIVERSITARIO", 8.00, 16.00);
    INSERT INTO PRODUCTOS (NOMBREPRODUCTO, COSTO, PRECIO)
    VALUES("CUADERNO", 8, 16);
    
    SELECT * FROM PRODUCTOS;
    DELIMITER $$
    CREATE TRIGGER TR_PRODUCTOS_BEFORE_UPDATE
    BEFORE UPDATE ON PRODUCTOS
    FOR EACH ROW
    BEGIN
		IF NEW.COSTO <> OLD.COSTO THEN
        SET NEW.PRECIO = NEW.COSTO *2;
        END IF;
    END $$
    DELIMITER ;
    
    UPDATE PRODUCTOS SET COSTO = 10 WHERE NOMBREPRODUCTO = "CUADERNO";
