USE BANCO;
CREATE VIEW VISTA_BANCO AS SELECT FECHA, ID_CLIENTE, TRANSACCION FROM HISTORIAL WHERE TRANSACCION >=1000;
SELECT * FROM VISTA_BANCO;
SELECT NOMBRE FROM CLIENTE
INNER JOIN HISTORIAL ON CLIENTE.ID_CLIENTE=HISTORIAL.ID_CLIENTE;

CREATE VIEW VISTA_CLIENTE AS SELECT * FROM CLIENTE;

CREATE VIEW VISTA_CUENTA AS SELECT * FROM CUENTA;

CREATE VIEW VISTA_DEPOSITOS AS SELECT * FROM DEPOSITOS;

CREATE VIEW VISTA_HISTORIAL AS SELECT * FROM HISTORIAL;

CREATE VIEW VISTA_PROVEEDORES AS SELECT * FROM PROVEEDORES;

CREATE VIEW VISTA_RETIROS AS SELECT * FROM RETIROS;

CREATE VIEW VISTA_SEGURO AS SELECT * FROM SEGURO;

CREATE VIEW VISTA_SERVIEMPRESAS AS SELECT * FROM SERVI_EMPRESAS;

CREATE VIEW VISTA_USUARIOS AS SELECT * FROM USUARIOS
